# Generated by Django 5.0.1 on 2025-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('CHEF', 'Chef'), ('STAFF', 'Staff'), ('SALAD_BAR', 'Salad Bar Station'), ('SANDWICH', 'Sandwich Station'), ('HOT_STATION', 'Hot Station'), ('COLD_STATION', 'Cold Station'), ('SHOPPING_ASSISTANT', 'Shopping Assistant')], default='STAFF', max_length=20),
        ),
    ]
