# Generated by Django 5.0.1 on 2025-03-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('SALAD_BAR', 'Salad Bar'), ('SANDWICH', 'Sandwich'), ('HOT_STATION', 'Hot Station'), ('ORDERER', 'Orderer')], default='ORDERER', max_length=20),
        ),
    ]
