# Generated by Django 5.0.13 on 2025-03-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_submit_shopping_orders',
            field=models.BooleanField(default=False, help_text='Allow this user to create shopping orders regardless of their role'),
        ),
    ]
