# Generated by Django 5.0.13 on 2025-03-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_can_submit_shopping_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('submit_shopping_order', 'Can submit shopping orders'), ('confirm_shopping_order', 'Can confirm shopping orders'), ('view_shopping_order', 'Can view shopping orders'), ('order_ingredients', 'Can order ingredients'), ('view_ingredient_order', 'Can view ingredient orders'), ('process_orders', 'Can process orders'), ('admin_full_access', 'Has full access to view and confirm everything')]},
        ),
    ]
