# Generated by Django 5.0.1 on 2025-03-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_prepped',
        ),
    ]
