# Generated by Django 5.0.1 on 2025-03-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_ingredient_is_prepped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='minimum_stock',
        ),
    ]
