# Generated by Django 5.0.1 on 2025-03-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ingredientorder_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientorder',
            name='section',
        ),
    ]
