# Generated by Django 5.0.1 on 2025-03-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_shoppingingredient_remove_shoppingorderitem_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
