# Generated by Django 5.0.13 on 2025-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ingredientorderitem_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorderitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
