# Generated by Django 5.0.13 on 2025-12-28 01:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_ingredientorder_order_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorderitem',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
